$(document).ready(function(){
    $("h3#one").click(function(q){
        q.preventDefault();
        $("#course1").toggle();
    });
});
$(document).ready(function(){
   $("h3#two").click(function(q){
       q.preventDefault();
       $("#course2").toggle();
   });
});
$(document).ready(function(){
   $("h3#three").click(function(q){
       q.preventDefault();
       $("#course3").toggle();
   });
});
$(document).ready(function(){
   $("h3#four").click(function(q){
       q.preventDefault();
       $("#course4").toggle();
   });
});
$(document).ready(function(){
   $("h3#five").click(function(q){
       q.preventDefault();
       $("#course5").toggle();
   });
});
$(document).ready(function(){
   $("h3#six").click(function(q){
       q.preventDefault();
       $("#course6").toggle();
   });
});

//TECHNOLOGY START
$(document).ready(function() {
   $("button#itA").click(function(q){
       q.preventDefault();
       $("#IT").toggle();
       $("#BA").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#cs").click(function(q){
       q.preventDefault();
       $("#CS").toggle();
       $("#IT").hide();
       $("#BA").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BAA").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#swe").click(function(q){
       q.preventDefault();
       $("#SWE").toggle();
       $("#CS").hide();
       $("#IT").hide();
       $("#BA").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BAA").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#cse").click(function(q){
       q.preventDefault();
       $("#CSE").toggle();
       $("#SWE").hide();
       $("#CS").hide();
       $("#IT").hide();
       $("#BA").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BAA").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#ds").click(function(q){
       q.preventDefault();
       $("#DS").toggle();
       $("#CSE").hide();
       $("#SWE").hide();
       $("#CS").hide();
       $("#IT").hide();
       $("#BA").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BAA").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
//TECHNOLOGY END

//BUSINESS START
$(document).ready(function() {
   $("#itB").click(function(){
       $("#BA").toggle();
       $("#IT").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#bc").click(function(){
       $("#BC").toggle();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#bm").click(function(){
       $("#BM").toggle();
       $("#BC").hide();
       $("#BIT").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#HE").hide();
       $("#MECH").hide(); 
       $("#BAA").hide(); 
       $("#CS").hide(); 
       $("#SWE").hide();     
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#bit").click(function(){
       $("#BIT").toggle();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#baa").click(function(){
       $("#BAA").toggle();
       $("#BIT").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
//BUSINESS END

//ECONOMICS START
$(document).ready(function() {
   $("button#acc").click(function(q){
       q.preventDefault();
       $("#accounting").toggle();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#re").click(function(q){
       q.preventDefault();
       $("#RE").toggle();
       $("#accounting").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#bf").click(function(q){
       q.preventDefault();
       $("#BF").toggle();
       $("#accounting").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#fe").click(function(q){
       q.preventDefault();
       $("#FE").toggle();
       $("#accounting").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#com").click(function(q){
       q.preventDefault();
       $("#COM").toggle();
       $("#FE").hide();
       $("#accounting").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
//ECONOMICS END

//ENGINEERING START
$(document).ready(function(){
   $("#mechEng").click(function(q){
       q.preventDefault();
       $("#ME").toggle();
       $("#MECH").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#accounting").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function(){
   $("button#ENG").click(function(q){
       q.preventDefault();
       $("#MECH").toggle();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#accounting").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function(){
   $("#ee").click(function(q){
       q.preventDefault();
       $("#EE").toggle();
       $("#MECH").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#accounting").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function(){
   $("#ce").click(function(q){
       q.preventDefault();
       $("#CE").toggle();
       $("#EE").hide();
       $("#MECH").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#accounting").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function(){
   $("#we").click(function(q){
       q.preventDefault();
       $("#WE").toggle();
       $("#CE").hide();
       $("#EE").hide();
       $("#MECH").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#accounting").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
//ENGINEERING END

//HUMANITIES START
$(document).ready(function(){
   $("#ge").click(function(q){
       q.preventDefault();
       $("#GE").toggle();
       $("#WE").hide();
       $("#CE").hide();
       $("#EE").hide();
       $("#MECH").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#accounting").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function(){
   $("#his").click(function(q){
       q.preventDefault();
       $("#HIS").toggle();
       $("#GE").hide();
       $("#WE").hide();
       $("#CE").hide();
       $("#EE").hide();
       $("#MECH").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#accounting").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function(){
   $("#se").click(function(q){
       q.preventDefault();
       $("#SE").toggle();
       $("#HIS").hide();
       $("#GE").hide();
       $("#WE").hide();
       $("#CE").hide();
       $("#EE").hide();
       $("#MECH").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#accounting").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function(){
   $("#rs").click(function(q){
       q.preventDefault();
       $("#RS").toggle();
       $("#SE").hide();
       $("#HIS").hide();
       $("#GE").hide();
       $("#WE").hide();
       $("#CE").hide();
       $("#EE").hide();
       $("#MECH").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#HE").hide();
       $("#accounting").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("button#itC").click(function(q){
       q.preventDefault();
       $("#LA").toggle();
       $("#BA").hide();
       $("#IT").hide();
       $("#accounting").hide();
       $("#HE").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
//HUMANITIES END

//ARTS START
$(document).ready(function() {
   $("#pd").click(function(q){
       q.preventDefault();
       $("#PD").toggle();
       $("#HE").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("button#econ").click(function(q){
       q.preventDefault();
       $("#HE").toggle();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#VID").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#vid").click(function(q){
       q.preventDefault();
       $("#VID").toggle();
       $("#HE").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#IDE").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#ide").click(function(q){
       q.preventDefault();
       $("#IDE").toggle();
       $("#VID").hide();
       $("#HE").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
       $("#MP").hide();
   })
})
$(document).ready(function() {
   $("#mp").click(function(q){
       q.preventDefault();
       $("#MP").toggle();
       $("#IDE").hide();
       $("#VID").hide();
       $("#HE").hide();
       $("#BA").hide();
       $("#IT").hide();
       $("#LA").hide();
       $("#accounting").hide();
       $("#MECH").hide();
       $("#BC").hide();
       $("#BM").hide();
       $("#BIT").hide();
       $("#BAA").hide();
       $("#CS").hide();
       $("#SWE").hide();
       $("#CSE").hide();
       $("#DS").hide();
       $("#FE").hide();
       $("#COM").hide();
       $("#BF").hide();
       $("#RE").hide();
       $("#ME").hide();
       $("#EE").hide();
       $("#CE").hide();
       $("#WE").hide();
       $("#GE").hide();
       $("#HIS").hide();
       $("#SE").hide();
       $("#RS").hide();
       $("#PD").hide();
   })
})
//ARTS END


$(document).ready(function() {
   $("#btn6").click(function(){
      alert("ThankYou for your interest, we'll get back at you shortly");
      window.location.href="../index.html";
   })
})

